name: Setup GitHub Secrets Guide

# This is a documentation workflow file to help set up required secrets
# It doesn't actually run any actions but serves as a guide

on:
  workflow_dispatch:
    inputs:
      documentation_only:
        description: 'This workflow is for documentation purposes only'
        required: true
        default: 'true'

jobs:
  document_required_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: List Required Secrets
        run: |
          echo "# LightRAG Required Secrets"
          echo ""
          echo "The following secrets need to be set up in your GitHub repository:"
          echo ""
          echo "## Docker Image Configuration"
          echo "- DOCKER_REGISTRY_HOST (default: ghcr.io)"
          echo "- DOCKER_IMAGE_NAME (default: ib-bsb-br/LightRAG)"
          echo "- IMAGE_TAG (default: latest)"
          echo ""
          echo "## Database Credentials"
          echo "- POSTGRES_USER (default: lightrag_user)"
          echo "- POSTGRES_PASSWORD (required, no default)"
          echo "- POSTGRES_DB (default: lightrag_db)"
          echo "- NEO4J_PASSWORD (required, no default)"
          echo ""
          echo "## OpenAI API Configuration"
          echo "- OPENAI_API_KEY (required, no default)"
          echo "- OPENAI_API_BASE (default: https://api.openai.com/v1)"
          echo "- LLM_MODEL (default: gpt-4o-mini)"
          echo "- EMBEDDING_MODEL (default: text-embedding-3-small)"
          echo "- EMBEDDING_DIM (default: 1536)"
          echo ""
          echo "## LightRAG Application Authentication & Settings"
          echo "- AUTH_ACCOUNTS (default: admin:AnotherStrongPassword123!)"
          echo "- TOKEN_SECRET (required, no default)"
          echo "- TOKEN_EXPIRE_HOURS (default: 4)"
          echo "- TIMEOUT (default: 300)"
          echo "- LOG_LEVEL (default: INFO)"
          echo "- ENABLE_LLM_CACHE_FOR_EXTRACT (default: true)"
          echo ""
          echo "## Server Configuration"
          echo "- HOST (default: 0.0.0.0)"
          echo "- PORT (default: 8000)"
          echo "- WEBUI_TITLE (default: 'My Graph KB')"
          echo "- WEBUI_DESCRIPTION (default: 'Simple and Fast Graph Based RAG System')"
          echo ""
          echo "## How to set up secrets in GitHub"
          echo "1. Go to your repository on GitHub"
          echo "2. Click on 'Settings' tab"
          echo "3. In the left sidebar, click on 'Secrets and variables' > 'Actions'"
          echo "4. Click on 'New repository secret'"
          echo "5. Enter the name of the secret (e.g., POSTGRES_PASSWORD)"
          echo "6. Enter the value for the secret"
          echo "7. Click 'Add secret'"
          echo "8. Repeat for all required secrets"
